version: '3'

services:
  api:
    build: .
    ports:
      - "5000:5000"
#    volumes:
#      - ./config.toml:/config.toml
    environment:
      - ENVIRONMENT=DEV
      - JAEGER_SERVICE_NAME=examples-basic
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=5775
    depends_on:
      - jaeger
    command:
      - ./wait-for-it.sh
      - jaeger:5775
      - --
      - app

  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - "5775:5775"   # UDP - accept zipkin.thrift over compact thrift protocol
      - "6831:6831"   # UDP - accept jaeger.thrift over compact thrift protocol
      - "6832:6832"   # UDP - accept jaeger.thrift over binary thrift protocol
      - "5778:5778"   # HTTP - serve configs
      - "16686:16686" # HTTP - serve frontend
      - "14268:14268" # HTTP - accept jaeger.thrift directly from clients
      - "9411:9411"   # HTTP - Zipkin compatible endpoint
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

#  prometheus:
#    image: prom/prometheus:latest
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#      - prometheus_data:/prometheus
#
#  grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"
#    environment:
#            - GF_SECURITY_ADMIN_PASSWORD=pass
#    depends_on:
#      - prometheus
#    volumes:
#      - grafana_data:/var/lib/grafana

#volumes:
#    prometheus_data: {}
#    grafana_data: {}