version: '3'

services:

  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - "5775:5775"   # UDP - accept zipkin.thrift over compact thrift protocol
      - "6831:6831"   # UDP - accept jaeger.thrift over compact thrift protocol
      - "6832:6832"   # UDP - accept jaeger.thrift over binary thrift protocol
      - "5778:5778"   # HTTP - serve configs
      - "16686:16686" # HTTP - serve frontend
      - "14268:14268" # HTTP - accept jaeger.thrift directly from clients
      - "9411:9411"   # HTTP - Zipkin compatible endpoint
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"